### Get all Vikings
GET http://localhost:8000/api/vikings/
Content-Type: application/json

###
GET http://localhost:8000/api/vikings/?page=1&limit=10
Content-Type: application/json

###
GET http://localhost:8000/api/vikings/?q=Aridon
Content-Type: application/json

###
GET http://localhost:8000/api/vikings/?desc=created_at
Content-Type: application/json

###
GET http://localhost:8000/api/vikings/?asc=name
Content-Type: application/json

###
GET http://localhost:8000/api/vikings/?page=2&limit=20&q=Aridon&desc=created_at
Content-Type: application/json

###
GET http://localhost:8000/api/vikings/?search_fields=description&q=A
Content-Type: application/json


### Get Viking by ID
GET http://localhost:8000/api/vikings/5
Content-Type: application/json

###

### Create a Viking
POST http://localhost:8000/api/vikings/
Content-Type: application/json

{
    "name": "Haki",
    "actor_name": "Haki",
    "description": "P9",
    "photo": "https://images.com"
}

###

### Update a Viking
PUT http://localhost:8000/api/vikings/5
Content-Type: application/json

{
    "name": "Aridon Updated",
    "actor_name": "Aridon",
    "description": "P9 Updated",
    "photo": "https://images.com"
}

###

### Delete a Viking
DELETE http://localhost:8000/api/vikings/8
Content-Type: application/json

###

### Scrape Vikings
POST http://localhost:8000/api/vikings/scrape/
Content-Type: application/json
