
services:
  frontend:
    build:
      context: .
    container_name: angular_frontend
    ports:
      - "4200:4200"
    networks:
      - app-network
      

networks:
  app-network:
    external: true
