version: '3.8'

services:
  frontend:
    build:
      context: .
    container_name: angular_frontend
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
