# Generated by Django 5.1.5 on 2025-01-30 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tv_series', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='viking',
            table='vikings',
        ),
    ]
