# Generated by Django 5.1.5 on 2025-01-30 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tv_series', '0002_alter_viking_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='nflplayer',
            table='nflplayers',
        ),
        migrations.AlterModelTable(
            name='nflplayerstats',
            table='nflplayerstats',
        ),
        migrations.AlterModelTable(
            name='norsemen',
            table='norsemens',
        ),
    ]
