# Generated by Django 5.1.5 on 2025-02-01 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tv_series', '0003_alter_nflplayer_table_alter_nflplayerstats_table_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Norsemen',
            new_name='Norseman',
        ),
        migrations.AlterModelTable(
            name='norseman',
            table='norsemans',
        ),
    ]
